### ISSUE TITLE
IDs in spec are challenging to remember

### ISSUE THREAD

**Issue by edithturn** [dokc/operator-feature-matrix#10]
IDs are challenging to remember. Things like: instm, mcrds, offin, scpua, coios, olmcl in Spec
https://github.com/dokc/operator-feature-matrix/blob/main/postgres/spec/feature_matrix.md
Thoughts: 

- Could it be something more readable?  “Install-mechanisms” instead of “instm”
- Is the character limit necessary (5 characters)? If there is a reason for this limit then the short name is understandable.

**Comment by ahachete** [comment]
This is intentional. IDs are meant only to uniquely identify each feature (think of them as a sort of PK if this would be a database). We could have used an autogenereated id field or a UUID for them, but it felt that using a short character description is a bit more enlightening than a pure surrogate key.

The IDs are not meant to understand the feature, that's what the `.name` field is. But since we want to provision the possibility that in the future even the name could change, yet being able to compare features, we need a stable, immutable identifier. This is why this IDs were chosen.

About the length, it was picked 4/5 chars for groups/features. Could this be extended to other lengths? Certainly. But since the name (plus the description) should provide a clear understanding of the feature, it was opted for the shortest possible ids so as to make renderings of the OFM not more wide than required (and they are quite wide already).

**Comment by edithturn** [comment]
Understood, @ahachete!
Thanks for the clarification on this point.

**Comment by ahachete** [comment]
I'll close the issue, feel free to reopen if you feel there's some further action to take here.
